services:
  # 🔹 Development
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: eduvate-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles: ["dev"]

  # 🔹 Production
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduvate-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
    profiles: ["prod"]
